### ISSUE TITLE
undefined method color

### ISSUE THREAD

**Issue by mare-imbrium** [davetron5000/hl#2]
I was trying out "hl". I keep getting this error:
undefined method `underline' for "rage":String

It comes from "highlight_string" in highlighter.rb. Each method gives an undefined error.

>  string = string.color(@options['color'].to_sym)

I know you've probably abandoned this project, but would be nice if you could check it out. Is it dependent on an old version of rainbow ?

thanks.
JK

**Comment by davetron5000** [comment]
I haven't abandoned it, just never needed to update it :)

Looks like Rainbow 2.0 changed a bunch of stuff.  Fix coming…
